### ISSUE TITLE
requestAnimationFrame

### ISSUE THREAD

**Issue by cusxio** [javivelasco/react-toolbox-airbnb#2]
Sorry to use issues this way, but looking through the code,

https://github.com/javivelasco/react-toolbox-airbnb/blob/c2e304450d7ec23b340b31f84343f09b3d6595c0/src/Airbnb/DatePicker/Pickers/MonthsWrapper.js#L48-L59

I was wondering, what is the purpose of wrapping the code block in requestAnimationFrame?

Thank you !

**Comment by javivelasco** [comment]
Sorry I don't really understand the question. That code is wrapped in a `requestAnimationFrame` because we have to wait for the next frame to measure the element so we make sure that it has been already updated.

**Comment by cusxio** [comment]
@javivelasco Oh sorry, there isn't a question.

Just wanted to know why the code needs to be wrapped in `requestAnimationFrame`.

Thank you!

**Comment by javivelasco** [comment]
Np! :D
